import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import { CursorEffects } from "@/components/ui/cursor-effects";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: "Sprout & About",
    description: "Generated by create next app",
};

const homemadeApple = localFont({
    src: "./fonts/HomemadeApple-Regular.ttf",
    variable: "--font-homemade-apple",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${homemadeApple.variable} antialiased min-h-screen`}
                suppressHydrationWarning
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="light"
                    enableSystem
                    disableTransitionOnChange
                >
                    <CursorEffects />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
